<a href="https://colab.research.google.com/github/Sirfowahid/Challange_DL/blob/main/CDL_Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch as t

Transpose

In [4]:
#using numpy
arrn = np.array([[1,2,3,4]])
arrnt = arrn.T

print(arrn)
print(arrnt)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [5]:
matn = np.array([[1,2,3,4],
                  [5,6,7,8]])
matnt = matn.T
print(matn)
print(matnt)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [6]:
arrt =t.tensor([[1,2,3,4]])
arrtt = arrt.T
print(arrt)
print(arrtt)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [7]:
arr2t = t.tensor([[1,2,3,4],
                  [5,6,7,8]])
arr2tt = arr2t.T
print(arr2t)
print(arr2tt)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
