<a href="https://colab.research.google.com/github/Sirfowahid/Challange_DL/blob/main/CDL_Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mathematics

In [1]:
import numpy as np
import torch as t

Transpose

In [2]:
#using numpy
arrn = np.array([[1,2,3,4]])
arrnt = arrn.T

print(arrn)
print(arrnt)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [3]:
matn = np.array([[1,2,3,4],
                  [5,6,7,8]])
matnt = matn.T
print(matn)
print(matnt)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [4]:
arrt =t.tensor([[1,2,3,4]])
arrtt = arrt.T
print(arrt)
print(arrtt)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [5]:
arr2t = t.tensor([[1,2,3,4],
                  [5,6,7,8]])
arr2tt = arr2t.T
print(arr2t)
print(arr2tt)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])


Dot Product

In [6]:
na1 = np.array([1,2,3,4])
na2  = np.array([2,4,6,8])
#using method
print(np.dot(na1,na2))
#via computation
print(np.sum(na1*na2))

60
60


In [7]:
ta1 = t.tensor([1,2,3,4])
ta2 = t.tensor([2,4,6,8])
#using method
print(t.dot(ta1,ta2))
#via calculation
print(t.sum(ta1*ta2))

tensor(60)
tensor(60)


Matrix Multiplication

In [8]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)

print(np.matmul(A,B))
print(A@B)

[[-1.58161411 -4.78580889 -0.84421412  0.34173957 -3.07945909]
 [ 0.55267773  0.97938533 -0.43734659 -0.21487387  1.30508417]
 [-0.15474629  3.65839471  1.05072731 -1.83728706  3.75786211]]
[[-1.58161411 -4.78580889 -0.84421412  0.34173957 -3.07945909]
 [ 0.55267773  0.97938533 -0.43734659 -0.21487387  1.30508417]
 [-0.15474629  3.65839471  1.05072731 -1.83728706  3.75786211]]


In [9]:
C = t.randn(3,4)
D = t.randn(4,5)
print(C@D)
print(t.matmul(C,D))

tensor([[ 1.6175, -2.0384, -0.8179, -0.4320, -0.2103],
        [ 0.2897, -1.0869, -1.8005, -4.1509, -3.0275],
        [-3.5674,  0.5900, -0.7340,  1.6977,  2.1288]])
tensor([[ 1.6175, -2.0384, -0.8179, -0.4320, -0.2103],
        [ 0.2897, -1.0869, -1.8005, -4.1509, -3.0275],
        [-3.5674,  0.5900, -0.7340,  1.6977,  2.1288]])


In [10]:
A = np.array([1,2,3,4])
print(A.dtype)
B = t.tensor(A)
print(B.dtype)
C = t.tensor(A,dtype=t.float)
print(C.dtype)

int64
torch.int64
torch.float32
